HELLO_RESPONSE = "elo"
INVALID_COMMAND_RESPONSE = "Nieznana komenda"
INVALID_ARGUMENT_RESPONSE = "Niepoprawny argument"
USER_ADDED_RESPONSE = "Gracz został dodany!"
USER_NOT_FOUND_RESPONSE = "Nie ma takiego użytkownika na tym serwerze"
RIOT_USER_NOT_FOUND_RESPONSE = "Podano nie poprawne RiotID"
RESETED_RESPONSE = "Zresetowano dane graczy"